# Generated by Django 4.0.4 on 2022-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=50)),
                ('stars', models.IntegerField()),
                ('reservation', models.BooleanField()),
            ],
        ),
    ]
