# Generated by Django 4.0.4 on 2022-05-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_title_alter_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publised',
            new_name='published',
        ),
    ]
